// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview This file defines a Genkit flow for searching documents (circulars, instructions, and regulations)
 * in a MongoDB Atlas database based on keywords and then analyzing and responding to user queries.
 *
 * - searchDocuments - A function that handles the document search process.
 * - SearchDocumentsInput - The input type for the searchDocuments function.
 * - SearchDocumentsOutput - The return type for the searchDocuments function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';
import {MongoClient, Db} from 'mongodb';

// Define the input schema
const SearchDocumentsInputSchema = z.object({
  query: z.string().describe('The user query to search for documents.'),
  documentType: z.enum(['circular', 'instruction', 'regulation']).describe('The type of document to search for.'),
  mongodbUri: z.string().describe('The MongoDB connection URI.'),
  mongodbDatabaseName: z.string().describe('The name of the MongoDB database.'),
  mongodbCollectionName: z.string().describe('The name of the MongoDB collection.'),
});
export type SearchDocumentsInput = z.infer<typeof SearchDocumentsInputSchema>;

// Define the output schema
const SearchDocumentsOutputSchema = z.object({
  results: z.array(
    z.object({
      _id: z.string(),
      link_acceso: z.string().optional(),
      resumen: z.string().optional(),
      titulo: z.string().optional(),
      tipo_normativa: z.string().optional(),
      numero: z.string().optional(),
      tema: z.string().optional(),
      palabras_clave: z.array(z.string()).optional(),
      fecha_expedicion: z.string().optional(),
      titulo_seccion: z.string().optional(),
      articulos: z
        .array(
          z.object({
            numero_articulo: z.string().optional(),
            resumen_articulo: z.string().optional(),
            palabras_clave_articulo: z.array(z.string()).optional(),
          })
        )
        .optional(),
    })
  ).describe('The search results from the database.'),
  answer: z.string().describe('The answer to the user query based on the search results.'),
});
export type SearchDocumentsOutput = z.infer<typeof SearchDocumentsOutputSchema>;

// Define the main function that will be called from the client
export async function searchDocuments(input: SearchDocumentsInput): Promise<SearchDocumentsOutput> {
  return searchDocumentsFlow(input);
}

// Define the prompt
const searchDocumentsPrompt = ai.definePrompt({
  name: 'searchDocumentsPrompt',
  input: {schema: SearchDocumentsInputSchema},
  output: {schema: SearchDocumentsOutputSchema},
  prompt: `You are an AI assistant designed to search and analyze documents from a database.

You will be provided with a user query, the type of document to search for (circular, instruction, or regulation), and the MongoDB connection details.

Your task is to:
1.  Connect to the MongoDB database using the provided URI, database name, and collection name.
2.  Search the specified collection for documents that match the user query based on keywords and/or resumen fields.
3.  Analyze the retrieved documents and provide a concise and informative answer to the user query.
4.  Include the link_acceso in your answer if available. If documentType is regulation always return 'https://personal.justucuman.gov.ar/pdf/Reglamento%20de%20Expediente%20Digital.pdf' as link.
5.  Do not use any external sources or hallucinate information.

Here is the information you will use:

User Query: {{{query}}}
Document Type: {{{documentType}}}

Here are the search results from the database:
{{{JSON.stringify results}}}


Answer:`,
});

// Define the flow
const searchDocumentsFlow = ai.defineFlow(
  {
    name: 'searchDocumentsFlow',
    inputSchema: SearchDocumentsInputSchema,
    outputSchema: SearchDocumentsOutputSchema,
  },
  async input => {
    // Connect to MongoDB
    const client = new MongoClient(input.mongodbUri);

    try {
      await client.connect();
      const db: Db = client.db(input.mongodbDatabaseName);
      const collection = db.collection(input.mongodbCollectionName);

      // Construct the search query based on the document type
      let searchQuery = {};

      if (input.documentType === 'regulation') {
        searchQuery = {
          $or: [
            { 'articulos.palabras_clave_articulo': { $in: [input.query] } },
            { 'articulos.resumen_articulo': { $regex: input.query, $options: 'i' } },
            { titulo_seccion: { $regex: input.query, $options: 'i' } },
          ],
        };
      } else {
        searchQuery = {
          $or: [
            { palabras_clave: { $in: [input.query] } },
            { resumen: { $regex: input.query, $options: 'i' } },
          ],
        };
      }

      // Search the collection
      const results = await collection.find(searchQuery).toArray();

      // Call the prompt with the search results
      const {output} = await searchDocumentsPrompt({
        ...input,
        results,
      });

      return output!;
    } finally {
      await client.close();
    }
  }
);
